### PR TITLE
fix generator size bug with reflection

### LINKED ISSUE #34: shouldGenerateObjectWithFieldsContainingSetterPrefix test not passing
shouldGenerateObjectWithFieldsContainingSetterPrefix test not passing in [this branch](https://github.com/oubaydos/java-random-instances-generator/blob/test_field_name_including_setter/src/test/java/io/javarig/RandomInstanceGeneratorTest.java).
seems working fine and passing when executed alone, but when executing all the tests, the min max size becomes different (>15) and not the default one (5-15)

### PR DESCRIPTION
**Pull request by HamzaBenyazid**

### CODE REVIEW

File: src/main/java/io/javarig/TypeEnum.java [hunk 1]
```diff
@@ -99,17 +91,12 @@ private static TypeEnum getObjectIfNotEnum(Type type) {
...
-    }
-
-    public void setType(Type type) {
-        if (this.generator instanceof TypeBasedGenerator typeBasedGenerator) {
-            typeBasedGenerator.setType(type);
+    public TypeGenerator createGeneratorInstance(Type type, RandomInstanceGenerator randomInstanceGenerator) {
+        try {
+            return (AbstractTypeGenerator) this.generatorClass.getConstructor(Type.class, RandomInstanceGenerator.class)
+                    .newInstance(type, randomInstanceGenerator);
+        } catch (ReflectiveOperationException e) {
```
Comment (oubaydos) [inline src/main/java/io/javarig/TypeEnum.java:99]: i think its better to throw a custom exception instead!

**Review by oubaydos — APPROVED** [review]
